name: 'Send HTML Email with SendGrid'
description: 'A custom GitHub Action to send HTML emails using SendGrid.'
author: 'Your Name'
inputs:
  sendgrid_api_key:
    description: 'SendGrid API Key'
    required: true
    secret: true
  from_email:
    description: 'Sender email address'
    required: true
  to_email:
    description: 'Recipient email address'
    required: true
  subject:
    description: 'Email subject'
    required: true
  html_content:
    description: 'HTML content for the email body'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sendgrid_api_key }}
    - ${{ inputs.from_email }}
    - ${{ inputs.to_email }}
    - ${{ inputs.subject }}
    - ${{ inputs.html_content }}
